@echo off
setlocal
cd /d "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos"
if not exist "luna" mkdir "luna"
ffmpeg -y -stream_loop -1 -i "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos\_loops\luna-speaking-loop.mp4" -i "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos\_audio\luna-01-criativo-a-solidao.mp3" -shortest -map 0:v:0 -map 1:a:0 -vf "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,format=yuv420p" -c:v libx264 -preset fast -crf 23 -c:a aac -b:a 128k -movflags +faststart "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos\luna\01-criativo-a-solidao.mp4"
if not exist "luna" mkdir "luna"
ffmpeg -y -stream_loop -1 -i "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos\_loops\luna-speaking-loop.mp4" -i "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos\_audio\luna-02-criativo-b-produtividade.mp3" -shortest -map 0:v:0 -map 1:a:0 -vf "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,format=yuv420p" -c:v libx264 -preset fast -crf 23 -c:a aac -b:a 128k -movflags +faststart "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos\luna\02-criativo-b-produtividade.mp4"
if not exist "luna" mkdir "luna"
ffmpeg -y -stream_loop -1 -i "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos\_loops\luna-speaking-loop.mp4" -i "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos\_audio\luna-03-desabafo-domingo.mp3" -shortest -map 0:v:0 -map 1:a:0 -vf "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,format=yuv420p" -c:v libx264 -preset fast -crf 23 -c:a aac -b:a 128k -movflags +faststart "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos\luna\03-desabafo-domingo.mp4"
if not exist "luna" mkdir "luna"
ffmpeg -y -stream_loop -1 -i "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos\_loops\luna-speaking-loop.mp4" -i "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos\_audio\luna-04-stories-10s.mp3" -shortest -map 0:v:0 -map 1:a:0 -vf "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,format=yuv420p" -c:v libx264 -preset fast -crf 23 -c:a aac -b:a 128k -movflags +faststart "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos\luna\04-stories-10s.mp4"
if not exist "leo" mkdir "leo"
ffmpeg -y -stream_loop -1 -i "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos\_loops\leo-speaking-loop.mp4" -i "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos\_audio\leo-01-criativo-a-solidao.mp3" -shortest -map 0:v:0 -map 1:a:0 -vf "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,format=yuv420p" -c:v libx264 -preset fast -crf 23 -c:a aac -b:a 128k -movflags +faststart "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos\leo\01-criativo-a-solidao.mp4"
if not exist "leo" mkdir "leo"
ffmpeg -y -stream_loop -1 -i "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos\_loops\leo-speaking-loop.mp4" -i "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos\_audio\leo-02-criativo-b-produtividade.mp3" -shortest -map 0:v:0 -map 1:a:0 -vf "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,format=yuv420p" -c:v libx264 -preset fast -crf 23 -c:a aac -b:a 128k -movflags +faststart "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos\leo\02-criativo-b-produtividade.mp4"
if not exist "leo" mkdir "leo"
ffmpeg -y -stream_loop -1 -i "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos\_loops\leo-speaking-loop.mp4" -i "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos\_audio\leo-03-desabafo-domingo.mp3" -shortest -map 0:v:0 -map 1:a:0 -vf "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,format=yuv420p" -c:v libx264 -preset fast -crf 23 -c:a aac -b:a 128k -movflags +faststart "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos\leo\03-desabafo-domingo.mp4"
if not exist "leo" mkdir "leo"
ffmpeg -y -stream_loop -1 -i "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos\_loops\leo-speaking-loop.mp4" -i "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos\_audio\leo-04-stories-10s.mp3" -shortest -map 0:v:0 -map 1:a:0 -vf "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,format=yuv420p" -c:v libx264 -preset fast -crf 23 -c:a aac -b:a 128k -movflags +faststart "C:\Users\Iury\OneDrive\Área de Trabalho\EGO-AI-APP - Copia\marketing\videos\leo\04-stories-10s.mp4"
echo Pronto.
