# Opcional se usar .env (recomendado). Se usar só isto, mantenha aspas na URL.

SUPABASE_URL = "https://enmjrrxueszgtcjiyobp.supabase.co"
SUPABASE_KEY = "sb_publishable_8MAoZCKOhDnh4xu5SlTwbw_i2Z_BgRs"
